[package]
name = "zippy"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3.2"
rand = "0.8.5"
rsa = "0.9.8"
sha2 = "0.10.9"
